### PR TITLE
Improve adapter into working django app

### PR DESCRIPTION
**Pull request by gerbyzation**
in response to #1 

I've done some work on the adapter to get it working with Django and restructured it a bit to be a valid django app. You can now add it to `INSTALLED_APPS` like any other django package. 

One issue is that the initialisation of the enforcer attempts to load all policies from database. The way django works this causes problems, as this would also execute before migrations can be applied, causing the code to query non-existing tables and crashing. 

At the moment I'm avoiding this by using a singleton that initialises the enforcer on the first call. I haven't found anything like a lifecycle hook in django that could be used for this (`AppConfig.ready()` should not have database queries as it still runs before management commands). I've just pinged off a message in the django IRC to see if there might be a better approach. Either way this should be documented or ideally a solution offered.

### CODE REVIEW

**Comment by gerbyzation** [comment]
Thought I'd also share a snippet on how I'm currently using it. There is definitely some room to improve the ergonomics.
```python
# authentication/logic.py
from casbin import Enforcer
from django.conf import settings

from casbin_adapter.adapter import Adapter

if settings.TESTING:
    adapter = settings.BASE_DIR + '/authorization/tests/empty.csv'
else:
    adapter = Adapter()

_enforcer = None

def enforcer():
    global _enforcer
    if _enforcer is None:
        _enforcer = Enforcer(settings.BASE_DIR + '/authorization/casbin.conf', adapter, settings.DEBUG)
    return _enforcer

def is_allowed(*, subject: str, resource: str, action: str) -> bool:
    return enforcer().enforce(subject, resource, action)
```

**Comment by hsluoyz** [comment]
@techoner @nodece please review.

**Comment by divy9881** [comment]
```3.7``` and ```3.8``` python builds are failing due to the fact, the ```unittest``` doesn't allow abuse in ```PEP 420```. And, I think, the Travis config is not consistent with your location of the test directory. Try bringing the test directory to the root level. I think this may solve this build issue.

**Comment by divy9881** [comment]
Frankly speaking, I have never seen this type of issue.

**Comment by hsluoyz** [comment]
@DivyPatel9881 the Travis CI error will be discussed at: https://github.com/pycasbin/django-orm-adapter/issues/3

**Comment by divy9881** [comment]
The travis build issue is specific to this PR, as @gerbyzation has moved tests directory in the casbin_adapter directory.

**Comment by hsluoyz** [comment]
OK. @gerbyzation can you fix the CI error? https://travis-ci.org/github/pycasbin/django-orm-adapter/builds/682985313

**Comment by gerbyzation** [comment]
@hsluoyz done

**Comment by hsluoyz** [comment]
lgtm. Thanks for you all! @gerbyzation @DivyPatel9881

**Pull request merged**
